FROM archive-base

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["celery", "-A", "app.core.queue:celery_app", "worker", "--loglevel=info", "--concurrency=2"]