version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: archive_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: archive_admin
      POSTGRES_PASSWORD: StrongPass123
      POSTGRES_DB: archive_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: archive_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: archive_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: StrongMinioPass123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web console

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: archive_elastic
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  openldap:
    image: osixia/openldap:1.5.0
    container_name: archive_ldap
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: "2 STC Army"
      LDAP_DOMAIN: "2stc.army.mil"
      LDAP_ADMIN_PASSWORD: LdapAdmin123
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"

volumes:
  postgres_data:
  minio_data:
  elastic_data:
  ldap_data:
  ldap_config: