services:

  postgres:
    image: postgres:16-alpine
    container_name: archive_postgres
    restart: always
    environment:
      POSTGRES_USER: archive_admin
      POSTGRES_PASSWORD: StrongPass123
      POSTGRES_DB: archive_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: archive_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: archive_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: StrongMinio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: archive_elastic
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  postgres_data:
  redis_data:
  minio_data:
  elastic_data: